apiVersion: v1
kind: Namespace
metadata:
  name: be-connect-establisher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: be-connect-establisher
  name: dep-be-connector
  labels:
    app: dep-be-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-connector
  template:
    metadata:
      labels:
        app: be-connector
    spec:
      containers:
      - name: be-connector
        image: ayratkhisamiev/peer-be-helper
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  namespace: be-connect-establisher
  name: service-be-connector
spec:
  selector:
    app: be-connector
  ports:
    - protocol: TCP
      port: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: be-connect-establisher
  name: ingress-be-connector
spec:
  ingressClassName: nginx
  rules:
    - host: be-peer-conenctor.red-tech.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-be-connector
                port:
                  number: 5000
  tls:
    - secretName: red-tech.cloud
      hosts:
        - "be-peer-conenctor.red-tech.cloud"