# apiVersion: v1
# kind: Namespace
# metadata:
#   name: be-connect-establisher
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: be-connect-establisher
  name: dep-turn
  labels:
    app: dep-turn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turn
  template:
    metadata:
      labels:
        app: turn
    spec:
      containers:
      - name: turn
        image: coturn/coturn
        ports:
          - containerPort: 3478
          - containerPort: 5349
          - containerPort: 49152:65535
---
apiVersion: v1
kind: Service
metadata:
  namespace: be-connect-establisher
  name: service-turn
spec:
  type: LoadBalancer
  loadBalancerIP: "85.31.236.92"
  clusterIP: None
  selector:
    app: turn
  ports:
    - protocol: TCP
      port: 3478
    - protocol: UDP
      port: 3478
    - protocol: UDP
      port: 5349
    - protocol: UDP
      port: 49152:65535